### PR TITLE
Dirty hack to find symbols out of hash

### PR DESCRIPTION
**Pull request by akawashiro**
This hack finds symbols out of hash.

### CODE REVIEW

**Review by shinh — COMMENTED** [review]
What kind of symbols are missing in `indices`?

**Comment by akawashiro** [comment]
For example, `nvrtcCompileProgram` in `libnvrtc.so.10.2`. You can check by
```
% build/print_dynsymtab /usr/local/cuda/lib64/libnvrtc.so.10.2 2>&1 | grep nvrtcCompileProgram
% build/print_dtrela /usr/local/cuda/lib64/libnvrtc.so.10.2 2>&1 | grep nvrtcCompileProgram
% nm -D /usr/local/cuda/lib64/libnvrtc.so.10.2 | grep nvrtcCompileProgram
00000000003acac0 T nvrtcCompileProgram
```

**Comment by shinh** [comment]
I believe `CollectSymbolsFromGnuHash` is wrong. See https://github.com/lattera/glibc/blob/master/elf/dl-lookup.c#L428

https://github.com/shinh/sold/pull/31

(I'm not sure why libnvrtc.so has broken chains, though)

**Comment by akawashiro** [comment]
This PR is closed because [PR31](https://github.com/shinh/sold/pull/31) resolved the problem.

**Pull request closed without merging**
